<?xml version="1.0"?>
<robot name="tri_steer" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- ========== 参数 ========== -->
  <xacro:property name="wheel_radius" value="0.05"/>
  <xacro:property name="body_radius" value="0.05"/>
  <xacro:property name="body_height" value="0.05"/>

  <xacro:property name="wheel_damping" value="0.0001"/>
  <xacro:property name="wheel_friction" value="0.0001"/>

  <xacro:property name="wheel_effot" value="300"/>
  <xacro:property name="wheel_velocity" value="20"/>

  <xacro:property name="turn_effot" value="300"/>
  <xacro:property name="turn_velocity" value="10"/>


  <xacro:property name="pos_wheel_z" value="-0.045"/>
  
  <xacro:property name="turn_radius" value="0.1"/>
  <xacro:property name="turn_height" value="0.01"/> 



  <xacro:property name="lift_radius" value="0.1"/>
  <xacro:property name="lift_height" value="0.02"/>

  <!-- 轮子到车体中心的半径（决定转弯时轮速差） -->
  <!-- <xacro:property name="R" value="0.3535"/> -->

  <!-- ========== base ========== -->
  <link name="base_footprint"/> 

  <link name="base_link">
    <inertial>
      <origin xyz="0.008137 0.051566 0.0019645" rpy="0 0 0" />
      <mass value="5.0701" />
      <inertia ixx="0.056129" ixy="-5.0766E-05" ixz="0.00012401" iyy="0.10521" iyz="-5.3268E-05" izz="0.054858" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0.0" rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://tri_steer_description/meshes/base_link.STL" />
      </geometry>
      <material
        name="">
        <color rgba="0.1 0.6 0.5 1" />
      </material>
    </visual>
        <collision>
      <origin
        xyz="0 0.1 0"
        rpy="1.5708 0 0" />
      <geometry>
       <cylinder radius="${turn_radius}" length="${turn_height}"/>
       </geometry>
    </collision>
  </link>

   <joint name="base_link_joint" type="fixed">
    <origin xyz="0 0 0.1" rpy="1.5708 0 3.1416"/>
    <parent link="base_footprint"/>
    <child link="base_link"/>
  </joint> 

  <!-- 舵轮 1 -->
    <link
    name="turn1">
    <inertial>
      <origin
        xyz="-8.1358E-05 0.088662 -0.0004925"
        rpy="0 0 0" />
      <mass
        value="3.2924" />
      <inertia
        ixx="0.006991"
        ixy="-1.731E-06"
        ixz="0.00016006"
        iyy="0.012782"
        iyz="-4.8359E-06"
        izz="0.0076006" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://tri_steer_description/meshes/turn1.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.79216 0.81961 0.93333 1" />
      </material>
    </visual>
  <collision>
  <origin xyz="0 0.05 0" rpy="1.5708 0 0"/>
  <geometry><cylinder radius="${turn_radius}" length="${turn_height}"/></geometry>
  </collision>

  </link>
  <joint
    name="joint11"
    type="continuous">
    <origin
      xyz="-0.35334 0 0"
      rpy="0 0 0" />
    <parent
      link="base_link" />
    <child
      link="turn1" />
    <axis
      xyz="0 -1 0" />
    <dynamics damping="${wheel_damping}" friction="${wheel_friction}"/>
    <limit effort="${turn_effot}" velocity="${turn_velocity}"/>
  </joint>
  <link
    name="wheel1">
    <inertial>
      <origin
        xyz="2.1316E-14 5.209E-14 0.043943"
        rpy="0 0 0" />
      <mass
        value="0.5" />
      <inertia
        ixx="0.00022144"
        ixy="3.1729E-19"
        ixz="2.4627E-18"
        iyy="0.00022144"
        iyz="3.3994E-17"
        izz="0.00034522" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://tri_steer_description/meshes/wheel1.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.79216 0.81961 0.93333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0.045"
        rpy="0 0 0" />
      <geometry>
       <sphere radius= "${wheel_radius}"/>
      </geometry>
    </collision>
  </link>
  <joint
    name="joint12"
    type="continuous">
    <origin
      xyz="0 -0.045 -0.045"
      rpy="0 0 0" />
    <parent
      link="turn1" />
    <child
      link="wheel1" />
    <axis
      xyz="0 0 1" />
    <dynamics damping="${wheel_damping}" friction="${wheel_friction}" />
    <limit effort="${wheel_effot}" velocity="${wheel_velocity}" />

  </joint>
  <link
    name="lift1">
    <inertial>
      <origin
        xyz="-0.00029755 -0.026187 -8.3752E-05"
        rpy="0 0 0" />
      <mass
        value="0.54659" />
      <inertia
        ixx="0.0014575"
        ixy="-2.8022E-07"
        ixz="-2.5959E-07"
        iyy="0.0026981"
        iyz="-6.4239E-07"
        izz="0.0014564" />
    </inertial>
    <visual>
      <origin
        xyz="0 0.105 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://tri_steer_description/meshes/lift1.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.79216 0.81961 0.93333 1" />
      </material>
    </visual>
    <collision>
    <origin xyz="0 ${0-lift_height/2+0.105} 0" rpy="1.5708 0 0"/>
      <geometry><cylinder radius="${lift_radius}" length="${lift_height}"/></geometry>
    </collision>
  </link>
  <joint
    name="joint13"
    type="prismatic">
    <origin
      xyz="0 0.095 0"
      rpy="0 0 0" />
    <parent
      link="turn1" />
    <child
      link="lift1" />
    <axis
      xyz="0 1 0" />
  <dynamics damping="0.2" friction="0.1"/>
  <limit lower="0" upper="0.05" effort="2000" velocity="0.1"/>

  </joint>

  <!-- 舵轮 2 -->
    <link
    name="turn2">
    <inertial>
      <origin
        xyz="-8.1358E-05 0.088662 -0.0004925"
        rpy="0 0 0" />
      <mass
        value="3.2924" />
      <inertia
        ixx="0.006991"
        ixy="-1.731E-06"
        ixz="0.00016006"
        iyy="0.012782"
        iyz="-4.8359E-06"
        izz="0.0076006" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://tri_steer_description/meshes/turn2.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.79216 0.81961 0.93333 1" />
      </material>
    </visual>
  <collision>
  <origin xyz="0 0.05 0" rpy="1.5708 0 0"/>
  <geometry><cylinder radius="${turn_radius}" length="${turn_height}"/></geometry>
  </collision>
  
  </link>
  <joint
    name="joint21"
    type="continuous">
    <origin
      xyz="0.17667 0 -0.306"
      rpy="0 0 0" />
    <parent
      link="base_link" />
    <child
      link="turn2" />
    <axis
      xyz="0 -1 0" />
    <dynamics damping="${wheel_damping}" friction="${wheel_friction}"/>
    <limit effort="${turn_effot}" velocity="${turn_velocity}"/>
  </joint>
  <link
    name="wheel2">
    <inertial>
      <origin
        xyz="-1.3045E-14 3.1183E-14 0.046057"
        rpy="0 0 0" />
      <mass
        value="0.5" />
      <inertia
        ixx="0.00022144"
        ixy="4.1394E-19"
        ixz="-2.8135E-19"
        iyy="0.00022144"
        iyz="6.5115E-17"
        izz="0.00034522" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://tri_steer_description/meshes/wheel2.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.79216 0.81961 0.93333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0.045"
        rpy="0 0 0" />
      <geometry>
       <sphere radius= "${wheel_radius}"/>
      </geometry>
    </collision>
  </link>
  <joint
    name="joint22"
    type="continuous">
    <origin
      xyz="0 -0.045 -0.045"
      rpy="0 0 0" />
    <parent
      link="turn2" />
    <child
      link="wheel2" />
    <axis
      xyz="0 0 1" />
    <dynamics damping="${wheel_damping}" friction="${wheel_friction}"/>
    <limit effort="${wheel_effot}" velocity="${wheel_velocity}"/>
  </joint>
  <link
    name="lift2">
    <inertial>
      <origin
        xyz="-6.5992E-05 -0.026187 -0.0003037"
        rpy="0 0 0" />
      <mass
        value="0.5466" />
      <inertia
        ixx="0.0014569"
        ixy="4.3412E-07"
        ixz="5.8934E-07"
        iyy="0.0026981"
        iyz="-5.5014E-07"
        izz="0.001457" />
    </inertial>
    <visual>
      <origin
        xyz="0 0.105 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://tri_steer_description/meshes/lift2.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.79216 0.81961 0.93333 1" />
      </material>
    </visual>
    <collision>
    <origin xyz="0 ${0-lift_height/2+0.105} 0" rpy="1.5708 0 0"/>
      <geometry><cylinder radius="${lift_radius}" length="${lift_height}"/></geometry>
    </collision>
  </link>
  <joint
    name="joint23"
    type="prismatic">
    <origin
      xyz="0 0.095 0"
      rpy="0 0 0" />
    <parent
      link="turn2" />
    <child
      link="lift2" />
    <axis
      xyz="0 1 0" />
  <dynamics damping="0.2" friction="0.1"/>
  <limit lower="0" upper="0.05" effort="2000" velocity="0.1"/>

  </joint>
  <link
    name="turn3">
    <inertial>
      <origin
        xyz="-8.1365E-05 0.088662 -0.00049252"
        rpy="0 0 0" />
      <mass
        value="3.2924" />
      <inertia
        ixx="0.006991"
        ixy="-1.731E-06"
        ixz="0.00016006"
        iyy="0.012782"
        iyz="-4.8359E-06"
        izz="0.0076006" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://tri_steer_description/meshes/turn3.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.79216 0.81961 0.93333 1" />
      </material>
    </visual>
  <collision>
  <origin xyz="0 0.05 0" rpy="1.5708 0 0"/>
  <geometry><cylinder radius="${turn_radius}" length="${turn_height}"/></geometry>
  </collision>
  </link>
  <joint
    name="joint31"
    type="continuous">
    <origin
      xyz="0.17667 0 0.306"
      rpy="0 0 0" />
    <parent
      link="base_link" />
    <child
      link="turn3" />
    <axis
      xyz="0 -1 0" />
    <dynamics damping="${wheel_damping}" friction="${wheel_friction}"/>
    <limit effort="${turn_effot}" velocity="${turn_velocity}"/>
  </joint>


  <link
    name="wheel3">
    <inertial>
      <origin
        xyz="-1.2934E-14 -7.1637E-14 -0.043943"
        rpy="0 0 0" />
      <mass
        value="0.5" />
      <inertia
        ixx="0.00022144"
        ixy="4.2629E-19"
        ixz="-2.7812E-19"
        iyy="0.00022144"
        iyz="5.1358E-17"
        izz="0.00034522" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://tri_steer_description/meshes/wheel3.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.79216 0.81961 0.93333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 -0.045"
        rpy="0 0 0" />
      <geometry>
       <sphere radius= "${wheel_radius}"/>
      </geometry>
    </collision>
  </link>


  <joint
    name="joint32"
    type="continuous">
    <origin
      xyz="0 -0.045 0.045"
      rpy="0 0 0" />
    <parent
      link="turn3" />
    <child
      link="wheel3" />
    <axis
      xyz="0 0 1" />
    <dynamics damping="${wheel_damping}" friction="${wheel_friction}"/>
    <limit effort="${wheel_effot}" velocity="${wheel_velocity}"/>
  </joint>
  <link
    name="lift3">
    <inertial>
      <origin
        xyz="-6.6075E-05 -0.026187 -0.00030366"
        rpy="0 0 0" />
      <mass
        value="0.5466" />
      <inertia
        ixx="0.0014569"
        ixy="4.3412E-07"
        ixz="5.8934E-07"
        iyy="0.0026981"
        iyz="-5.5014E-07"
        izz="0.001457" />
    </inertial>
    <visual>
      <origin
        xyz="0 0.105 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://tri_steer_description/meshes/lift3.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.79216 0.81961 0.93333 1" />
      </material>
    </visual>
    <collision>
    <origin xyz="0 ${0-lift_height/2+0.105} 0" rpy="1.5708 0 0"/>
      <geometry><cylinder radius="${lift_radius}" length="${lift_height}"/></geometry>
    </collision>
  </link>
  <joint
    name="joint33"
    type="prismatic">
    <origin
      xyz="0 0.095 0"
      rpy="0 0 0" />
    <parent
      link="turn3" />
    <child
      link="lift3" />
    <axis
      xyz="0 1 0" />
    <dynamics damping="0.2" friction="0.1"/>
    <limit lower="0" upper="0.05" effort="2000" velocity="0.1"/>

</joint>

  <!-- ========== 激光雷达 link（用于 TF 和外观）========== -->
  <link name="laser">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-4" ixy="0" ixz="0" iyy="1e-4" iyz="0" izz="1e-4"/>
    </inertial>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.03" length="0.05"/>
      </geometry>
      <material name="Gray">
        <color rgba="0.6 0.6 0.6 1"/>
      </material>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.03" length="0.05"/>
      </geometry>
    </collision>
  </link>

  <!-- laser 固定到 base_link 上（根据你雷达实际安装位置改 xyz） -->
  <joint name="laser_joint" type="fixed">
    <parent link="base_link"/>
    <child link="laser"/>
    <!-- 例：雷达在车体前方 0.20m，高 0.12m -->
    <origin xyz="0.0 0.5 0.0" rpy="1.5708 0 0"/>
    <!-- <origin xyz="0.0 0.5 0.0" rpy="1.5708 0 0"/> -->
  </joint>

<!-- ========== Gazebo 激光传感器：发布 /scan ========== -->
<gazebo reference="laser">
  <sensor type="ray" name="laser_sensor">
    <pose>0 0 0 0 0 0</pose>
    <!-- 雷达扫描射线是否可见 -->
    <!-- <visualize>true</visualize> -->
    <!-- 雷达更新频率 -->
    <update_rate>10</update_rate>

    <ray>
      <scan>
        <horizontal>
          <samples>1440</samples>
          <resolution>1</resolution>
          <min_angle>-3.14</min_angle>  <!-- -90deg -->
          <max_angle> 3.14</max_angle>  <!-- +90deg -->
        </horizontal>
      </scan>
      <range>
        <min>0.10</min>
        <max>10.0</max>
        <resolution>0.01</resolution>
      </range>
      <noise>
        <type>gaussian</type>
        <mean>0.0</mean>
        <stddev>0.01</stddev>
      </noise>
    </ray>

    <plugin name="gazebo_rplidar" filename="libgazebo_ros_laser.so">
      <!-- 使用ros包仿真，使用/scan -->
      <topicName>/scan</topicName>
      <!-- 如果需要使用ros包仿真的话，注释掉/laser_scan，平时使用/laser_scan -->
      <!-- <topicName>/laser_scan</topicName> -->
      <frameName>laser</frameName>
    </plugin>
  </sensor>
</gazebo>



    <!-- Gazebo friction for wheel -->
    <gazebo reference="wheel1">
      <mu1>250</mu1>
      <mu2>250</mu2>
      <kp>200000</kp>
      <kd>1200</kd>
      <material>Gazebo/Black</material>
    </gazebo>

    <gazebo reference="wheel2">
      <mu1>250</mu1>
      <mu2>250</mu2>
      <kp>200000</kp>
      <kd>1200</kd>
      <material>Gazebo/Black</material>
    </gazebo>

    <gazebo reference="wheel3">
      <mu1>250</mu1>
      <mu2>250</mu2>
      <kp>200000</kp>
      <kd>1200</kd> 
      <material>Gazebo/Black</material>
    </gazebo>


    <gazebo reference="turn1">
      <material>Gazebo/Green</material>
    </gazebo>

    <gazebo reference="turn2">
      <material>Gazebo/Green</material>
    </gazebo>

  <gazebo reference="turn3">
      <material>Gazebo/Green</material>
    </gazebo>


  <!-- ===== transmissions for tri_steer ros_control ===== -->

  <!-- steer joints: Position -->
  <transmission name="steer_1_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint11">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="steer_1_motor">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="steer_2_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint21">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="steer_2_motor">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="steer_3_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint31">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="steer_3_motor">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <!-- wheel joints: Velocity -->
  <transmission name="wheel_1_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint12">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="wheel_1_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="wheel_2_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint22">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="wheel_2_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="wheel_3_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint32">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="wheel_3_motor">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>


  <!-- lift joints: Position (如果你要控升降就保留；暂时不用也可以先不启 controller) -->
  <transmission name="lift_1_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint13">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="lift_1_motor">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="lift_2_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint23">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="lift_2_motor">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="lift_3_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint33">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="lift_3_motor">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <!-- ========== Gazebo ros_control 插件 ========== -->
  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/</robotNamespace>
      <robotParam>/robot_description</robotParam>
      <rosDebugLevel>Debug</rosDebugLevel>
      <!-- 防止gazebo与robot_state_publisher冲突以下两者设定为false -->
      <publishWheelTF>false</publishWheelTF>
      <publishTf>1</publishTf>
      <publishWheelJointState>false</publishWheelJointState>
      <updateRate>10.0</updateRate>

      <!-- 里程计话题 -->
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <odometryRate>100.0</odometryRate>   <!-- 更新速度 -->
      <robotBaseFrame>base_footprint</robotBaseFrame>   <!-- 根坐标系 -->
      <cmdVelTimeOut>0.25</cmdVelTimeOut>
      <publishOdometryTf>1</publishOdometryTf>

      <broadcastTF>1</broadcastTF>
    </plugin>
  </gazebo>

  <!-- 以下是使用gazebo插件获取机器人位置真值的插件 -->
  <gazebo>
    <plugin name="p3d_base_controller" filename="libgazebo_ros_p3d.so">
      <alwaysOn>true</alwaysOn>
      <updateRate>100.0</updateRate>
      <bodyName>base_footprint</bodyName>
      <topicName>truthPose</topicName>
      <gaussianNoise>0.0</gaussianNoise>
      <frameName>map</frameName>
      <xyzOffsets>0 0 0</xyzOffsets>
      <rpyOffsets>0 0 0</rpyOffsets>
    </plugin>
  </gazebo>
  
</robot>